### ISSUE TITLE
Symlink option not properly configured

### ISSUE THREAD

**Issue by winklerrr** [mihneadb/node-directory-tree#108]
The `followSymlinks` options is not properly set (there is no default value).
Further, there is a typo in `index.d.ts`, the option is missing an `s` at the end.

**Comment by winklerrr** [comment]
No, sorry

**Comment by mihneadb** [comment]
* The default value logic does work as it's checking for an explicit `false` setting. Will follow by default.
* Fixed the typo in `index.d.ts` via 5f7536c138b (3.2.2)
