### ISSUE TITLE
Cannot find name 'IObj'

### ISSUE THREAD

**Issue by rankida** [mihneadb/node-directory-tree#122]
Hello 👋 

It appears a recent change has broken the typings for this module.

I am getting the following error which I think is related to https://github.com/mihneadb/node-directory-tree/pull/121 where the `IObj` interface was removed but is still used at [index.d.ts#L37](https://github.com/mihneadb/node-directory-tree/blob/master/index.d.ts#L37).

I will try to open a PR today, but I wanted to raise this issue now.

Thanks for the effort and great work maintaining an OSS package takes 🙇

**Comment by mihneadb** [comment]
Hey, oops, you're right. Thanks a lot for the help! Is there any way to somehow cover things like these while testing?

**Comment by rankida** [comment]
Hi @mihneadb , I have added an example of how to test this [in my PR here](https://github.com/mihneadb/node-directory-tree/pull/123/files#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519R36). 

Feel free to use or throw it away.

**Comment by mihneadb** [comment]
Makes sense, merging, thanks!
