### ISSUE TITLE
Does not return Symlinks

### ISSUE THREAD

**Issue by devpixde** [mihneadb/node-directory-tree#127]
Is there a way to return Symlinks to files? I need a tree that returns Symlinks the same way as files. Is there an option to achieve this?

Strangely i get Symlinks in case there is a hardlink to the same file (with other name) in same directory. 

PS: I found the option "followSymlinks" in code, but it seems to handle only directory Symlinks. Symlinks to files seem to be ignored.

**Comment by mihneadb** [comment]
Hi! It might be that similar to `isFile()` [here](https://github.com/mihneadb/node-directory-tree/blob/master/lib/directory-tree.js#L94), there might be a need to handle something for symlinks.

**Comment by devpixde** [comment]
line 64
`
  try {
    stats = FS.statSync(path);
    lstat = FS.lstatSync(path);
  }
  catch (e) { return null }
`
if path is a Symlink to a file we get an error here and return null for the item.

Will try to fix it later...

**Comment by devpixde** [comment]
Problem was that i did not have proper symlinks. They where created with relative paths, which does not work in this case. If i use absolute paths symlinks to files are handled just like files.
