### ISSUE TITLE
Publish a new release

### ISSUE THREAD

**Issue by amio** [mihneadb/node-directory-tree#15]
It's been 4 months and lots of fixes since 1.0.0, consider publish a new release?

**Comment by mihneadb** [comment]
Absolutely, it was on my TODO list, just been away. Doing it now, thanks! :) Will close the issue when done.

**Comment by mihnea-dobrescubalaur-hs** [comment]
Done, thanks for the reminder! https://www.npmjs.com/package/directory-tree
