### ISSUE TITLE
create directory structure for child path

### ISSUE THREAD

**Issue by sarora2073** [mihneadb/node-directory-tree#31]
Hi,

This package is super useful! 

Wondering if you think it might be easy to enhance this package to index a child path instead of the entire provided path? 

e.g. if i store user specific documents like this:

user1/files/folderA
user2/files/folderB

var data = directoryTree(username+'/files', ['.txt']);

I want the generated directory tree to have paths as follows, without the parent path:

e.g. for user1:
'files/folderA'
NOT 'user1/files/folderA'
This is for security reasons, as i have a client-side application that receives the directory tree data, but it should never know about the existence of parent folders like user1, user2 etc. 

I imagine, the new approach to provide child subpaths only would need to support a new parameter like so:

var data = directoryTree(parentPath, subPath, ['.txt']);

e.g. in my use case I would invoke as follows:
var data = directoryTree(username,'/files', ['.txt']);

I'm glad to do a PR if you think this would be a useful addition. Any pointers appreciated!

Best Regards,

-S. Arora

**Comment by mihneadb** [comment]
Hi,
I think what you want is doable with just calling `directoryTree` for each of the user folders and merging the results. How does that sound?

**Comment by sarora2073** [comment]
The problem I'm trying to describe is that the full path of whatever I call directoryTree on should not be returned. I need to pass the full path obviously, but I need the result to be a subpar. Makes sense?

**Comment by mihneadb** [comment]
Sure. You can simply walk the results with a recursive function and remove the prefix of that subpath.

**Comment by sarora2073** [comment]
I was thinking to fix the package code rather than cleansing the path. Please let me know if you think it's worth doing a PR for.

**Comment by mihneadb** [comment]
I think this doesn't belong in the package and it is something that the caller should handle. Should it become a more often requested enhancement, we can reconsider. Closing this. :beers:

**Comment by sarora2073** [comment]
Fair enough.  At least for my purposes I've made the change here:: https://github.com/sarora2073/node-directory-tree. It's a breaking change as-is (because it adds a new parameter), but if others request it I can look into making the change without breaking the existing approach (i.e. make new parameter optional).

**Comment by mihneadb** [comment]
:+1: happy you got your problem addressed!

**Comment by leoj3n** [comment]
If this isn't going to be included perhaps an example of removing the subPath added to the README would help because I thought it was possible based on the examples given in the README.

**Comment by leoj3n** [comment]
Additionally to what @sarora2073 proposed, perhaps another ergonomic feature would be detecting paths that start with `./` and assuming a subpath of the current directory.

**Comment by djnorrisdev** [comment]
> Additionally to what @sarora2073 proposed, perhaps another ergonomic feature would be detecting paths that start with `./` and assuming a subpath from the current directory.

That wouldn't work (at least for linux and mac) with how the source code is currently looking at the root of the project where this package is installed. For example`const tree = dirTree('md')` and const tree = dirTree('./md') find the same path based off of the root directory. It still seems the easiest two ways to deal with this is are: 1) to regex or substring out the top level directory. 
Keep in mind this method needs to check for type (directory or file) and if there's no second level directory, it may be valuable to keep the top level directory in the path; it's all up to user preference though.
