### ISSUE TITLE
Add file date last updated

### ISSUE THREAD

**Issue by calebeaires** [mihneadb/node-directory-tree#36]
[ ] bug
[x] feature request

---------

NodeJS has support to get time modified of an file. Here is an example on how to do it.

```javascript
fs.stat("/dir/file.txt", function(err, stats){
    var mtime = new Date(util.inspect(stats.mtime));
    console.log(mtime);
});
```

Can you consider put this feature to node-directory-tree?

**Comment by mihneadb** [comment]
Hi! Maybe you could think of a way to use the callback support for this? Or maybe add a more generic way in which you could return more data in the JSON if you wanted to?

**Comment by calebeaires** [comment]
Right now I'm doing this:

```js

const fs = require('fs');
const dirTree = require('directory-tree');
const util = require('util');
//...
getTree() {
      const tree = dirTree(dir);

      tree.children.forEach((file, key) => {
        const stats = fs.statSync(file.path);
        const date = new Date(util.inspect(stats.birthtime));
        tree.children[key].date = date;
      });

      return tree;
}
```

**Comment by mihneadb** [comment]
Seems reasonable enough to me. I wouldn't be for adding mtime because then you get into the discussion of what else to add. Again, if you come up with a more generic way of adding custom fields to the nodes, please send in a PR! 

Thanks!
