### ISSUE TITLE
Allow multiple excludes

### ISSUE THREAD

**Issue by dp-1a** [mihneadb/node-directory-tree#38]
Hi,

would it be possible to add the possibility to specify multiple excludes and extensions?

I´m currently trying to parse nodejs/typescript projects and they often contain a lot of "metadata" which I would like to ignore. For example I would like to ignore  `node_modules` and an output folder like `dist`.

Basically make the `exclude` option accept an array of regexes...

Thx

**Comment by mihneadb** [comment]
Hi, sounds good, feel free to submit a PR!

Thanks!

**Comment by david-j-davis** [comment]
Is this live? When I install I'm getting directory-tree version 2.0. This feature returns an error when I use it: TypeError: options.exclude.test is not a function.

**Comment by dp-1a** [comment]
Hi, looking at the PR again - this feature should only be available with `2.1.0`. With `2.0.0` this feature is not active.

**Comment by david-j-davis** [comment]
Right, and 2.1.0 isn't available to install on npm.

**Comment by dp-1a** [comment]
True, but that is something which @mihneadb needs to take care of :)

**Comment by david-j-davis** [comment]
Ok. @mihneadb, greatly appreciate this npm package. Any plan to update npm with the latest package?

**Comment by mihneadb** [comment]
Sorry about that, answered on the issue. Published.
