### ISSUE TITLE
can i mutate item before get tree ?

### ISSUE THREAD

**Issue by crapthings** [mihneadb/node-directory-tree#40]
i try to change each item with callback

return new obj or change item doesn't do anything.

```
return dirTree(url || process.cwd().split('/.meteor')[0], {} , (i, p) => {
 return { title: i.name, ...etc }
})
```

**Comment by mihneadb** [comment]
The return value of the callback is not used. https://github.com/mihneadb/node-directory-tree/blob/master/lib/directory-tree.js#L47

**Comment by rmdwirizki** [comment]
So is it possible to mutate the item @mihneadb?

**Comment by rmdwirizki** [comment]
Well, in my case I don't have to worry about performance, so I just mutate the item right after getting the tree.

```js
const fs = require('fs');
const dirTree = require('directory-tree');

const tree = dirTree('./data-example/imba-docs');
const walk = function(node) {
  if(node.children) {
    for (let index = 0; index < node.children.length; index++) {
      walk(node.children[index]);
    }
  }
  
  // Mutate here
  delete node['size']; 

  return node;
}

const mutatedTree = walk(tree);
console.log(JSON.stringify(mutatedTree, null, 2));
```

**Comment by rmdwirizki** [comment]
Sorry my bad, I forgot about javascript variable reference. it seems you can mutate item before get the tree by directly modifying the `item` variable.

```js
const tree = dirTree('./data-example/imba-docs', {
  extensions:/\.(md|json)/,
  exclude:/(tree|tree-clean).json/
}, (item, PATH) => {
  // Modify item
  item = Object.assign(item, {}, {
    id: shortid.generate()
  })
});
})
```

This issue should be closed.

**Comment by mihneadb** [comment]
Glad you found a way!
FWIW I don't think it's worth doing `item = ...`, you can just call `Object.assign` and ignore its return value.
