### ISSUE TITLE
saving results of callback

### ISSUE THREAD

**Issue by punund** [mihneadb/node-directory-tree#51]
Would you consider adding the resut of callback function to the item?
Patch would be trivial, something along the lines
````
-                       onEachFile(item, PATH);
+                       const results = onEachFile(item, PATH);
+                       if (results !== undefined)
+                               item.data = results;
````

**Comment by mihneadb** [comment]
You have access to `item` in the callback so you should be able to set an attribute from within it.
I'm thinking that should be enough, since I don't know how popular a pattern this is. Wdyt?

**Comment by punund** [comment]
You are right, I can do that.  Just seems a little un-functional having to modify a parameter.

**Comment by mihneadb** [comment]
I agree, it's not pure. I'd be OK with a variant of what you suggested as well if you think it's crucial at this point. Feel free to send a PR if so! :) 🥂
