### ISSUE TITLE
[New Feature] - Sort by type!

### ISSUE THREAD

**Issue by jcs090218** [mihneadb/node-directory-tree#52]
Hi, I just want to request a new feature if possible. I know the plugin sort the JSON data with alphabetical order. I think it would be nice if can sort with alphabetical order plus sort it with file type. :D 

Thx!

**Comment by mihneadb** [comment]
Hi, the code does nothing explicit to sort the results. The result is a tree-like object, so I'm not sure how sorting would look like. I'd suggest you implement a function to sort the returned tree. What do you think?

**Comment by jcs090218** [comment]
Hmmm, interesting! I thought you sort the paths alphabetically by default because the result I get from my web application is sort in alphabetic order, so I assume that you could change the sorting algorithm to whatever you what. My bad, I can just implement this myself. I thought it would be a great idea to have some filter like this. Thanks for answering my concern! If you not planning on adding stuff like this, just close this issue it if you want!

**Comment by mihneadb** [comment]
It's just the way the `fs` module returns items. Indeed, at this point I don't think it makes sense to have this included in the lib.

Feel free to share the function you end up writing here, it might be useful to others too! Thanks!

**Comment by jcs090218** [comment]
Okay, this is what I meant for sorting the either by `file` or by `directory` type.

```js
/**
 * Sort the tree result by directory/file type.
 * @param { tree.children } tree : Tree children.
 * @param { string } type : Sort type, enter 'directory' or 'file'.
 */
function sortTreeByType(tree, type = 'directory') {
  let tarList = [];  // target list.
  let anoList = [];  // another list.

  /* Split path object into two arrays by type. */
  {
    for (let index = 0;
         index < tree.length;
         ++index)
    {
      let pathObj = tree[index];
      if (pathObj.children != null && pathObj.children.length != 0) {
        sortTreeByType(pathObj.children, type);
      }

      // Add path object by type.
      if (pathObj.type == type)
        tarList.push(pathObj);
      else
        anoList.push(pathObj);
    }
  }

  /* Copy array over. */
  {
    let resultTree = tarList.concat(anoList);

    for (let index = 0;
         index < tree.length;
         ++index)
    {
      tree[index] = resultTree[index];
    }
  }
}
```

The default action will sort into this.
```
1d
1f.txt
2d
2f.txt
3d
3f.txt
4d
4f.txt
```
By calling this function will sort into this.
```
1d
2d
3d
4d
1f.txt
2f.txt
3f.txt
4f.txt
```
or 
```
1f.txt
2f.txt
3f.txt
4f.txt
1d
2d
3d
4d
```

P.S. `f` represent `file`, `d` represent `directory`. 

Hope this helps!

**Comment by Szymon-dziewonski** [comment]
@jcs090218 Thank you for this snippet, it saved a lot of my time :)
