### ISSUE TITLE
Updating tree after deleting or creating a file?

### ISSUE THREAD

**Issue by Molnfront** [mihneadb/node-directory-tree#6]
Hi,
I have a small problem, probably not directly related to your module, but when I delete or create a new file programmatically in the directory that node-directory-tree is fetching information from it is not updated. 

First I thought that it was my Angular app that was not refreshing the view, but I get the impression that it is the node server that is not updating. 

Only If I stop and start the server it will pick up the changes.

This is my little script:

app.get('/api/readtree', function(req, res) {
// we have to put the json in an array to get the right format to use in Angular tree.
var theArray = [];
theArray.push(repotree);
res.json(theArray);
console.log(theArray);
});

Is there a way to make the server unlock from the file system without  a restart?

**Comment by Molnfront** [comment]
I my have a solution. I remember an application that I built a year ago where I read files from a directory outside the node servers root. I had no problems whatsoever to read new files without restarting node.js. I will do a couple of tests...

**Comment by Molnfront** [comment]
I did a little test by changing to a directory outside the server root. But that did not work, then I built a little function based on my own working file reader and it works! The file list gets updated. Tested with Postman.

```
// test read files!
app.get('/readsomefiles' , function(req, res){
  var fileList = [];
  console.log('headers:' + req.headers.test);
  //Lista alla filer i /filer/ och gör en array av det.
  fs.realpath(repodir + '/', function(err, path) {
    if (err) {
      console.log(err);
      return;
    }
    //console.log('Path is : ' + path);
  });
// __dirname + '/filer/'
  fs.readdir(repodir + '/', function(err, files) {
    if (err) return;
  //console.log('vad: ' + files )
  //	fileList.push(files);

  for( i in files ){
    //console.log("test" + files[i]);
    fileList.push({'name': files[i]});
  }
  // send
  res.send(JSON.stringify(fileList));
});
});
```

Looks as if I have to build my own directory-tree traversal solution. I have no idea why one works and the other is not...

**Comment by Molnfront** [comment]
SOLVED! 
My bad, my implementation of your modul was a bit wrong, I declared to many variables. So it would hold the the listing forever I guess.
```
var dirTree = require('directory-tree');
var repotree = dirTree.directoryTree(repodir); <--- this will hold the value forever...
```
Now I tested this:
```
res.json(dirTree.directoryTree(repodir));
```
I had a

**Comment by mihneadb** [comment]
I'm glad you figured it out! Cheers!
