### ISSUE TITLE
Write results to .json file?

### ISSUE THREAD

**Issue by oscady** [mihneadb/node-directory-tree#60]
Apologies I think this might be a limitation of Nodejs as a whole but I am trying to replace a Python script I have running on my server that writes a JSON file out of the contents of a directory. Am I wrong to believe this can be done with node?

This package gives me a lovely output, I just can't figure out how I can write that output to a file once the script has run

Thanks

Osc

**Comment by mihneadb** [comment]
Hi, I think you need a combination of [this](https://stackoverflow.com/questions/2496710/writing-files-in-node-js) and [JSON.stringify](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/JSON/stringify).

**Comment by oscady** [comment]
Thanks I will have a look into that now

**Comment by zoiii** [comment]
Hi, might help.

`
const PATH = require('path');
const fs = require('fs');
const dirTree = require('directory-tree');

const folders = [];
const tree = dirTree('/path/directory'', null, (item, PATH, stats) => {
  folders.push(item);
});
fs.writeFileSync('output.json', JSON.stringify(folders));
`

**Comment by marcbrigham** [comment]
when I used the code above I got `folder\\folder\\testfile.svg`. Not sure why there is double `//`

**Comment by marcbrigham** [comment]
I needed to use `const PATH = require('path');
const fs = require('fs');
const dirTree = require('directory-tree');

const folders = [];
const tree = dirTree('./folder', {normalizePath:true}, null, (item, PATH, stats) => {
    folders.push(item);
    console.log(folders);
});
fs.writeFileSync('output.json', JSON.stringify(folders));`
