### ISSUE TITLE
Get folder only results.

### ISSUE THREAD

**Issue by shijianjian** [mihneadb/node-directory-tree#62]
Hi,

Thank you for the pretty simple plugin.

In my application, I care about the folder structure only. I therefore do not want to include the final files. Is there a easy way to select?

For example, I am now getting:
```
-- Folder A
    -- Folder B
        -- FileA.doc
        ...
    -- Folder C
        -- FileA.doc
        ...
```
While, what I want is:
```
-- Folder A
    -- Folder B
    -- Folder C
```
I wish to filter the files out.

**Comment by mihneadb** [comment]
Hi, you should be able to write a recursive function that only keeps items with `children`.

**Comment by cope** [comment]
@shijianjian:

```
const _ = require('lodash');
const dirTree = require("directory-tree");
const removeFiles = (children) => {
	return _.filter(children, child => {
		if (child.children) child.children = removeFiles(child.children);
		return child.type !== "file"
	});
};
const tree = dirTree("some_path");
tree.children = removeFiles(tree.children);
```
