### ISSUE TITLE
How to eliminate empty folders from the output

### ISSUE THREAD

**Issue by moda20** [mihneadb/node-directory-tree#69]
I want to try and eliminate the empty folders from the output, the ones that don't have any children not just directly inside but also in their children and the children of their children. 

basically if 

Folder A has no children, I don't want to see it in the output.
if Folder A has Folder B and Folder C as children, and both of them have no children, I want folder A to be emitted from the output. 

IS there anyway that is already built in your library, a small hack maybe ? that can help me do this ?
does the folder callback handle this case ?

**Comment by mihneadb** [comment]
Hi, the library can't do what you are asking at this point. You'd have to walk the resulting tree and filter it yourself with some recursive algorithm (or similar).

**Comment by g45t345rt** [comment]
Example of recursive algorithm for removing empty folders
https://gist.github.com/g45t345rt/22a356fdba70a04932db2c37a0f9691a
