### ISSUE TITLE
Add id field

### ISSUE THREAD

**Issue by stijnvddonk** [mihneadb/node-directory-tree#76]
Is it possible to add the option for an id to each item?

**Comment by mihneadb** [comment]
How would that work? Like a randomly generated id? Might be best to simply traverse the resulting tree and add them. I don't really see the need for this being part of the lib.
What do you think?

**Comment by stijnvddonk** [comment]
> How would that work? Like a randomly generated id? Might be best to simply traverse the resulting tree and add them. I don't really see the need for this being part of the lib.
> What do you think?

Hmm okay, yeah i thought like the first folder is 1, first nested 2 etc. I just started programming so im still figuring some stuff out. How would i achieve it using traverse?

**Comment by mihneadb** [comment]
Something like this - https://en.wikipedia.org/wiki/Breadth-first_search
Keep a counter of things you saw and assign ids based on it.
