### ISSUE TITLE
Circular symlink casues infinite loop

### ISSUE THREAD

**Issue by airarrazaval** [mihneadb/node-directory-tree#89]
As the title says, circular symbolic links causes an infinite loop.  To replicate this issue you can do the following:

```sh
mkdir test
cd test
ln -s . symlink
```

Then in your script if you run the following:

```js
const directoryTree = require('directory-tree');

directoryTree('/path/to/test/folder');
```

**Comment by mihneadb** [comment]
Fixed in #90. Thanks!
