### ISSUE TITLE
Namespace 'directoryTree' has no exported member 'Stats'.

### ISSUE THREAD

**Issue by mariaortiz0401** [mihneadb/node-directory-tree#91]
Hi! We're using directory-tree and we update daily the `node_modules` folder in our projects.
Today, we got this error when running `npm run build`

```js
node_modules/directory-tree/index.d.ts:25:41 - error TS2694: Namespace 'directoryTree' has no exported member 'Stats'.
25 attributes ? : (keyof directoryTree.Stats)[];
```

We got to solve it returning to the 2.2.9 version. 
Our versions are: 
```
node is v14.17.0 
npm 6.14.13
```

**Comment by mihneadb** [comment]
@mariaortiz0401 thanks for reporting this! Please try again with 2.3.1, I pushed [I hope] a fix.

**Comment by mariaortiz0401** [comment]
It works now. Thank you so much!
