### ISSUE TITLE
[Question] Release strategy

### ISSUE THREAD

**Issue by rijkvanzanten** [mihneadb/node-directory-tree#96]
Hi there!

Based on the version number structure, I wrongly assumed this package was SemVer, but it seems like versions are bumped (both major and minor) without any actual changes made (for example, see [the difference between 2.4.0 and 3.0.0](https://github.com/mihneadb/node-directory-tree/compare/2.4.0...3.0.0)). 

Is this package's version number tied to something I'm missing? 

Thanks!

**Comment by mihneadb** [comment]
Hi! Your assumption is correct. I made a mistake bumping the version after the default attributes change so I had to fix it. 
https://github.com/mihneadb/node-directory-tree/pull/93#issuecomment-924828277

**Comment by rijkvanzanten** [comment]
Ahh gotcha! Missed your previous explanation 🙂 

Thanks for the explanation and keep up the great work! ❤️
