### ISSUE TITLE
Missing properties `type` and `extension` in v3.0.0

### ISSUE THREAD

**Issue by pklaschka** [mihneadb/node-directory-tree#97]
First of all: Thank you for this tremendously helpful package.

In one of the previous releases (2.3.2 or 3.0.0, it wasn't present in v2.3.1), it seems that the `extension` and `type` properties of tree nodes aren't present in the results any longer (see screenshot above).

Since the `README.md` doesn't reflect this, I'm not sure if it's a bug or not... But if you intended to change it this way, it would probably be good to change the README accordingly (cf. https://github.com/mihneadb/node-directory-tree#result), and maybe add some notes about the breaking changes 🙂.

Excerpt from the results we got:

![image](https://user-images.githubusercontent.com/25147704/135178737-f573eb29-3c7a-43b2-9198-30a25def5e78.png)

### Temporary (?) workarounds:

Instead of checking `node.type === 'directory'` we now check for the presence of the `children` array (`if (node.children)`. For the extension, depending on the use case, we either use NodeJS's `path` module's native functions or, for simpler use cases, just check `node.name.endsWith('.yourextension')`.

Again, thanks for the library and have a pleasant day 🙂

**Comment by mihneadb** [comment]
Hey! I know we did update the readme after that change. Here's a screenshot:
<img width="1134" alt="Screenshot 2021-09-29 at 16 41 12" src="https://user-images.githubusercontent.com/643127/135280302-314c43b1-3451-41c3-a34c-0f7f451cb191.png">

Basically the default attributes changed and now you need to explicitly ask for type and/or extension.

**Comment by pklaschka** [comment]
Ah, ok, thanks for your response.

I will be honest: I completely missed this. It might make sense to add a bold "from version 3.0 forward, you'll have to specify additional attributes using ..." or something like this, there (since it's different from the previous version and scanning over the README, as it is, didn't get this info to me, unfortunately)...

Don't get me wrong: It's not a huge deal (it is documented, after all), it's just that this caused some rather "strange looking" errors for us and made debugging a little difficult, especially since there's no "changelog" that documents this change => it's easy to miss this change "as is".

That's just a suggestion, of course, the issue itself is resolved since it's intended (=> I'm closing this issue). Thanks again for your work and your quick response 🙂

**Comment by MichalLytek** [comment]
@mihneadb The typings says:
```
attributes ? : (keyof Stats)[];
```
So TS yells when I try to provide `["size", "type", "extension"]` 🤔

**Comment by mihneadb** [comment]
Hi, thanks for reporting. Fixed in https://github.com/mihneadb/node-directory-tree/commit/639b2c8d3b185936828b0b82e51feb433e24ceaa, published 3.0.1.
