### ISSUE TITLE
dirTree attributes and Typescript 

### ISSUE THREAD

**Issue by cdupetit** [mihneadb/node-directory-tree#98]
Hello @mihneadb,

The typings says: 
```
attributes ? : (keyof Stats)[];
```

So when you provide ["size", "type", "extension"], TS yells because he doesn't know about "type" and "extension" because they are not part of Stats declaration.
Please fix.
Thanks in advance.
Cyril 

_Originally posted by @MichalLytek in https://github.com/mihneadb/node-directory-tree/issues/97#issuecomment-931501632_

**Comment by mihneadb** [comment]
Hi, thanks for reporting. Fixed in https://github.com/mihneadb/node-directory-tree/commit/639b2c8d3b185936828b0b82e51feb433e24ceaa, published 3.0.1.
